# ------------------------------------------------------------------------------------------------------
# - Analysis Method: fisher, DRaWR, or net_path -
# ------------------------------------------------------------------------------------------------------
#method: net_path
method: {{ analysis_method }}

# --------------------------------------------------------------------
# - 4 col edge adjacency dataframe in .tsv format                    -
# - spreadsheet          dataframe in .tsv format                    -
# - phenotype            dataframe in .tsv format                    -
# --------------------------------------------------------------------
#gg_network_name_full_path:  ../data/networks/STRING_experimental_gene_gene.edge
#pg_network_name_full_path:    ../data/networks/kegg_pathway_property_gene.edge
#spreadsheet_name_full_path: ../data/spreadsheets/ProGENI_rwr20_STExp_GDSC_500.rname.gxc.tsv
#gene_names_map: ../data/spreadsheets/ProGENI_rwr20_STExp_GDSC_500_MAP.rname.gxc.tsv

gg_network_name_full_path:  {{ gg_network_name_full_path }}
pg_network_name_full_path:    {{ pg_network_name_full_path }}
spreadsheet_name_full_path: {{ spreadsheet_name_full_path }}
gene_names_map: {{ gene_names_map }}

# --------------------------------------------------------------------
# - directory where the result and temporary files will be written   -
# --------------------------------------------------------------------
#results_directory:          ./run_dir/results

results_directory:          {{ results_directory }}

# --------------------------------------------------------------------
# - maximum number of iterations without convergence                 -
# - convergence tolerance using frobenius norm                       -
# - rwr_restart_probability:   Vn+1 = alpha*N*Vn + (1-alpha)*Vo      -
# --------------------------------------------------------------------
#rwr_max_iterations:         500
#rwr_convergence_tolerence:  0.0001
#rwr_restart_probability:    0.5 # same as alpha in the above formula 

rwr_max_iterations:         {{ rwr_max_iterations }}
rwr_convergence_tolerence:  {{ rwr_convergence_tolerence }}
rwr_restart_probability:    {{ rwr_restart_probability }}


# --------------------------------------------------------------------
# - number of dimensions of the new space in SVD                     -
# --------------------------------------------------------------------
#k_space: 100    

k_space:  {{ k_space }}
