apiVersion: batch/v1
kind: Job
metadata:
  name: hello-py
spec:
  template:
    metadata:
      name: hello-py
    spec:
      containers:
      - name: cisrun
        image: testcropsinsilico/yggdrasil
        imagePullPolicy: Never
        args: [ "$(YAML_FILES)" ]
        env:
        - name: RABBIT_HOST
          value: "$(RABBITMQ_SERVICE_HOST)"
        - name: RABBIT_NAMESPACE
          value: "apiserver"
        - name: YAML_FILES
          value: "/usr/local/lib/python3.8/site-packages/yggdrasil/examples/hello/hello_python.yml"
      restartPolicy: Never
