apiVersion: batch/v1
kind: Job
metadata:
  name: hello-cpp
spec:
  template:
    metadata:
      name: hello-cpp
    spec:
      containers:
      - name: cisrun
        image: bodom0015/cis_interface
        args: [ "$(YAML_FILES)" ]
        env:
        - name: RABBIT_HOST
          value: "$(RABBITMQ_SERVICE_HOST)"
        - name: RABBIT_NAMESPACE
          value: "apiserver"
        - name: YAML_FILES
          value: "/usr/local/lib/python3.6/site-packages/cis_interface/examples/hello/hello_cpp.yml"
      restartPolicy: Never
