apiVersion: batch/v1
kind: Job
metadata:
  name: dc-test
spec:
  template:
    metadata:
      name: dc-test
    spec:
      containers:
      - name: data-cleanup
#        image: knowengdev/data-cleanup_pipeline:04_17_2017
        image: bodom0015/data-cleanup
        volumeMounts:
        - mountPath: /home/test/run_dir
          name: rundir
      volumes:
      - name: rundir
        hostPath:
          path:  /var/glfs/global/jobs/data-cleanup/
      restartPolicy: Never
