# A Docker compose file to simplify building up the images required to run the knoweng pipeline

version: '3'
services:
  # Framework / Models
  cis-interface:
    build: ./framework/
    image: testcropsinsilico/yggdrasil

  # IDE
  cis-cloud9:
    build:
      context: ./platform/dev
      dockerfile: Dockerfile.cloud9
      args:
        - verbose
    image: testcropsinsilico/cloud9

  # Platform
  cis-ui:
    build:
      context: https://github.com/astro-friedel/cis-ui.git
    image: testcropsinsilico/cis-ui:latest
    ports:
     - "80:80"
  girder:
    build:
      context: https://github.com/astro-friedel/cis-girder-plugin.git
    image: testcropsinsilico/girder:latest
    ports:
     - "8080:8080"
