# A Docker compose file to cimplify building up the images required to run the knoweng pipeline

version: '2'
services:
  gene-prioritization:
    build: ./pipelines/gene-prioritization
    image: bodom0015/gene-prioritization

  gene-set-characterization:
    build: ./pipelines/gene-set-characterization
    image: bodom0015/gene-set-characterization

  samples-clustering:
    build: ./pipelines/samples-clustering
    image: bodom0015/samples-clustering

  data-cleanup:
    build: ./pipelines/data-cleanup
    image: bodom0015/data-cleanup

  cloud9:
    build: ./platform/
    image: bodom0015/cloud9-nest
