# A Docker compose file to cimplify building up the images required to run the knoweng pipeline

version: '2'
services:
  # Pipelines
  cis-interface:
    build: ./framework/
    image: bodom0015/cis_interface

  # IDE
  cis-cloud9:
    build: ./platform/
    image: bodom0015/cloud9-cis
    
  # Platform
  cis-ui:
    build: ./docker/Dockerfile-nest_flask
    image: bodom0015/nest:flask
  cis-rabbitmq:
    image: "rabbit:3.6.12"
    ports: 
     - "5672:5672"
