# A Docker compose file to simplify building up the images required to run the knoweng pipeline

version: '3'
services:
  # Framework / Models
  cis-interface:
    build: ./framework/
    image: cropsinsilico/cis_interface

  # IDE
  cis-cloud9:
    build:
      context: ./platform/
      dockerfile: Dockerfile.cloud9
    image: cropsinsilico/cloud9
    
  # Platform
  cis-ui:
    build: 
      context: https://github.com/cropsinsilico/cis-ui.git
    image: cropsinsilico/cis-ui
    ports:
     - "80:80"
  girder:
    build:
      context: https://github.com/cropsinsilico/cis-girder-plugin
    image: cropsinsilico/girder:latest
    ports:
     - "8080:8080"
