# A Docker compose file to simplify building up the images required to run the knoweng pipeline

version: '3'
services:
  # Framework / Models
  cis-interface:
    build: ./framework/
    image: cropsinsilico/cis_interface

  # IDE
  cis-cloud9:
    build:
      context: ./platform/
      dockerfile: Dockerfile.cloud9
    image: cropsinsilico/cloud9
    
  # Platform
  cis-ui:
    build: 
      context: https://github.com/cropsinsilico/cis-ui.git
    image: cropsinsilico/cis-ui
  cis-api:
    build: 
      context: https://github.com/cropsinsilico/cis-apiserver.git
    image: cropsinsilico/cis-apiserver
  noflo-ui:
    image: flowhub/noflo-ui
    ports:
     - "9999:9999"
  cis-rabbitmq:
    image: "rabbit:3.6.12"
    ports: 
     - "5672:5672"
