apiVersion: batch/v1
kind: Job
metadata:
  name: gsc-{{ jobid }}
spec:
  template:
    metadata:
      name: gsc-{{ jobid }}
    spec:
      containers:
      - name: gsc-{{ jobid }}
        image: knowengdev/geneset_characterization_pipeline:04_07_2017
        command: ["/suppl/entrypoint.gsc.sh"]
        volumeMounts:
        - mountPath: /suppl
          name: suppl
        - mountPath: /home/test/run_dir
          name: rundir
      volumes:
      - name: suppl
        hostPath: /home/core/suppl
      - name: rundir
        hostPath: /home/core/local_results
      restartPolicy: Never
