# ------------------------------------------------------------------------------------------------------
# - Analysis Method: correlation, net_correlation, bootstrap_correlation, or bootstrap_net_correlation -
# ------------------------------------------------------------------------------------------------------
#method: bootstrap_net_correlation
method: {{ analysis_method }}

# ------------------------------------------------------------------------------------------------------
# - Correlation Method: pearson, t_test -
# ------------------------------------------------------------------------------------------------------
#correlation_measure: pearson
correlation_measure: {{ correlation_method }}

# --------------------------------------------------------------------
# - 4 col edge adjacency dataframe in .tsv format                    -
# - spreadsheet          dataframe in .tsv format                    -
# - phenotype            dataframe in .tsv format                    -
# --------------------------------------------------------------------
#gg_network_name_full_path:  ../data/networks/TEST_1_gene_gene.edge
#spreadsheet_name_full_path: ../data/spreadsheets/TEST_1_gene_sample.tsv
#phenotype_name_full_path:    ../data/spreadsheets/TEST_multi_drug_response_pearson.txt
gg_network_name_full_path:  {{ gg_network_name_full_path }}
spreadsheet_name_full_path: {{ spreadsheet_name_full_path }}
phenotype_name_full_path:    {{ phenotype_name_full_path }}

# --------------------------------------------------------------------
# - directory where the result and temporary files will be written   -
# --------------------------------------------------------------------
results_directory:          ./run_dir/results

# --------------------------------------------------------------------
# - Number of random samplings                                       -
# - Fraction of rows selected at random                              -
# - Fraction of columns selected at random                           -
# --------------------------------------------------------------------
#number_of_bootstraps:       20
number_of_bootstraps:       {{ number_of_bootstraps }}
#cols_sampling_fraction:     0.9 # 0.9 means 90% of columns    
cols_sampling_fraction:     {{ cols_sampling_fraction }}

# --------------------------------------------------------------------
# - maximum number of iterations without convergence                 -
# - convergence tolerance using frobenius norm                       -
# - rwr_restart_probability:   Vn+1 = alpha*N*Vn + (1-alpha)*Vo      -
# --------------------------------------------------------------------
#rwr_max_iterations:         100
rwr_max_iterations:         {{ rwr_max_iterations }}
#rwr_convergence_tolerence:  1.0e-2
rwr_convergence_tolerence:  {{ rwr_convergence_tolerence }}
#rwr_restart_probability:    0.5 # same as alpha in the above formula 
rwr_restart_probability:    {{ rwr_restart_probability }}

# --------------------------------------------------------------------
# - fraction to retain after first random walk smoothing             -
# --------------------------------------------------------------------
#top_beta_of_sort:           3
top_beta_of_sort:           {{ top_beta_of_sort }}
