# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cis-job-submission
subjects:
- kind: ServiceAccount
  name: cis
  namespace: cis
- kind: ServiceAccount
  name: cis
  namespace: cis-dev
- kind: ServiceAccount
  name: cis
  namespace: cis-staging
roleRef:
  kind: ClusterRole
  name: job-submission
  apiGroup: rbac.authorization.k8s.io
