# ------------------------------------------------------------------------------------------------------
# - Analysis Method: nmf, cc_nmf, net_nmf, cc_net_nmf                                                  -
# ------------------------------------------------------------------------------------------------------
#method: cc_net_nmf     
method: {{ analysis_method }}


# ------------------------------------------------------------------------------------------------------
# - Gene x Gene Network stored in 4 col format;   Gene x Set-id Spreadsheet
# ------------------------------------------------------------------------------------------------------
#gg_network_name_full_path: ../data/networks/keg_ST90_4col.edge
#spreadsheet_name_full_path: ../data/spreadsheets/tcga_ucec_somatic_mutation_data.df
#phenotype_name_full_path:   ../data/spreadsheets/UCEC_phenotype.txt
#threshold:                10

gg_network_name_full_path:  {{ gg_network_name_full_path }}
spreadsheet_name_full_path: {{ spreadsheet_name_full_path }}
phenotype_name_full_path:    {{ phenotype_name_full_path }}
threshold: {{ threshold }}


# --------------------------------------------------------------------
# - directory where the result and temporary files will be written   -
# --------------------------------------------------------------------
#results_directory:          ./run_dir/results
#tmp_directory:            ./run_dir/tmp

results_directory:     {{ results_directory }}
tmp_directory:         {{ tmp_directory }}


# --------------------------------------------------------------------
# - Number of sub-samples included in consensus                      -
# - Estimated number of clusters                                     -
# - Fraction of rows selected at random                              -
# - Fraction of columns selected at random                           -
# --------------------------------------------------------------------
#number_of_cluster: 3
#number_of_bootstraps:      4
#rows_sampling_fraction:     0.8 # 0.8 means 80% of rows    
#cols_sampling_fraction:     0.8 # 0.8 means 80% of columns    

number_of_clusters:         {{ number_of_clusters }}
number_of_bootstraps:       {{ number_of_bootstraps }}
rows_sampling_fraction:     {{ rows_sampling_fraction }}  
cols_sampling_fraction:     {{ cols_sampling_fraction }}


# --------------------------------------------------------------------
# - iterations between loop invariance checks; 
# - loop exit test;
# - absolute max loops;
# - network weighting factor
# --------------------------------------------------------------------
#nmf_conv_check_freq: 50
#nmf_max_invariance: 200
#nmf_max_iterations: 10000
#nmf_penalty_parameter: 1400

nmf_conv_check_freq: {{ nmf_conv_check_freq }}
nmf_max_invariance: {{ nmf_max_invariance }}
nmf_max_iterations: {{ nmf_max_iterations }}
nmf_penalty_parameter: {{ nmf_penalty_parameter }}


# --------------------------------------------------------------------
# - maximum number of iterations without convergence                 -
# - convergence tolerance using frobenius norm                       -
# - rwr_restart_probability:   Vn+1 = alpha*N*Vn + (1-alpha)*Vo      -
# --------------------------------------------------------------------
#rwr_max_iterations:         100
#rwr_convergence_tolerence:  0.0001
#rwr_restart_probability:    0.7 # same as alpha in the above formula 

rwr_max_iterations:         {{ rwr_max_iterations }}
rwr_convergence_tolerence:  {{ rwr_convergence_tolerence }}
rwr_restart_probability:    {{ rwr_restart_probability }}

# TODO: Below this line is all magic - ask Matt/Daniel about it?
#top_number_of_genes:        100
top_number_of_genes: {{ top_number_of_genes }}

# processing_method dictionary, valid values are serial, parallel, dist_comp
# single core machine: set the processing_method value to be serial
# multi core machine: set the processing_method value to be parallel
# multi node machine: set the processing_method value to be dist_comp 
#processing_method: serial

processing_method: {{ processing_method }}


#phenotype_name_full_path: ../data/spreadsheets/UCEC_phenotype.txt

# AWS configuration
cluster_ip_address:
# AWS env
- 172.31.47.99
- 172.31.41.138
# Dev env
#- 192.17.176.156
#- 192.17.176.151
#- 192.17.176.158
#- 192.17.176.161
#- 192.17.176.152
#- 192.17.176.150
#- 128.174.244.71

# AWS configuration
#cluster_shared_ram: /mnt/ramdisk/knoweng/
cluster_shared_ram: {{ cluster_shared_ram }}
# AWS configuration
#cluster_shared_volumn: /mnt/clustershare/knoweng/
cluster_shared_volumn: {{ cluster_shared_volume }}
