apiVersion: v1
kind: Service
metadata:
  labels:
    component: cis-ui
  name: cis-ui
spec:
  ports:
  - port: 3000
  selector:
    component: cis-ui
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: cis-ui
  name: cis-ui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: cis-ui
    spec:
      containers:
      - image: bodom0015/cis-ui
        name: cis-ui
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 100m
        volumeMounts:
        - name: data
          mountPath: /app/public/data
      volumes:
      - name: data
        hostPath:
          path: /home/core/cis-startup/data
