apiVersion: v1
kind: Service
metadata:
  name: cloud9 
  labels:
    component: cloud9
spec:
  selector:
    component: cloud9
  ports:
    - port: 8001
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: cloud9
spec:
  replicas: 1
  selector:
    component: cloud9
  template:
    metadata:
      labels:
        component: cloud9
    spec:
      volumes:
       - hostPath:
            path: "/home/ubuntu"
         name: src
       - hostPath:
            path: "/var/run/docker.sock"
         name: dockersock
       - hostPath:
            path: "/usr/bin/docker"
         name: dockerbin
      containers:
      - name: cloud9 
        image: bodom0015/cloud9-cis:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        volumeMounts:
          - name: src
            mountPath: "/cloud9/workspace"
          - name: dockersock
            mountPath: "/var/run/docker.sock"
          - name: dockerbin
            mountPath: "/bin/docker"
        env:
        - name: C9_EXTRA
          value: "--collab"
        ports:
        - containerPort: 8080
          protocol: TCP
