apiVersion: v1
kind: Service
metadata:
  name: cloud9 
  labels:
    component: cloud9
spec:
  selector:
    component: cloud9
  ports:
    - port: 80
      protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloud9
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: cloud9
    spec:
      volumes:
       - hostPath:
            path: "/home/core"
         name: src
       - hostPath:
            path: "/var/run/docker.sock"
         name: dockersock
       - hostPath:
            path: "/usr/bin/docker"
         name: dockerbin
       - hostPath:
            path: "/run/torcx"
         name: runtorcx
       - hostPath:
            path: "/run/metadata"
         name: runmetadata
      containers:
      - name: cloud9 
        image: ndslabs/cloud9-all:latest
        securityContext:
          privileged: true
        volumeMounts:
          - name: src
            mountPath: "/workspace"
          - name: dockersock
            mountPath: "/var/run/docker.sock"
          - name: dockerbin
            mountPath: "/usr/bin/docker"
          - name: runtorcx
            mountPath: "/run/torcx"
          - name: runmetadata
            mountPath: "/run/metadata"
        env:
        # Enable collaborative editing
        - name: C9_EXTRA
          value: "--collab"
        ports:
        - containerPort: 80
          protocol: TCP
