apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cloud9
  annotations:
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: basic-auth
    ingress.kubernetes.io/auth-realm: "Authentication Required"
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - cloud9.knowdev2.knowhub.org
    secretName: cloud9-tls-secret
  rules:
  - host: cloud9.knowdev2.knowhub.org
    http:
      paths:
      - path: /
        backend:
          serviceName: cloud9
          servicePort: 8001
      - path: /ide
        backend:
          serviceName: cloud9
          servicePort: 8001
      - path: /vfs/
        backend:
          serviceName: cloud9
          servicePort: 8001
      - path: /static/
        backend:
          serviceName: cloud9
          servicePort: 8001
      - path: /_ping
        backend:
          serviceName: cloud9
          servicePort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: cloud9 
  labels:
    component: cloud9
spec:
  selector:
    component: cloud9
  ports:
    - port: 8001
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: cloud9
spec:
  replicas: 1
  selector:
    component: cloud9
  template:
    metadata:
      labels:
        component: cloud9
    spec:
      volumes:
       - hostPath:
            path: "/home/ubuntu/"
         name: src
       - hostPath:
            path: "/var/run/docker.sock"
         name: dockersock
       - hostPath:
            path: "/usr/bin/docker"
         name: dockerbin
      containers:
      - name: cloud9 
        image: bodom0015/cloud9-nest:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
          - name: src
            mountPath: "/cloud9/workspace"
          - name: dockersock
            mountPath: "/var/run/docker.sock"
          - name: dockerbin
            mountPath: "/bin/docker"
        env:
        - name: C9_EXTRA
          value: "--collab"
        ports:
        - containerPort: 8080
          protocol: TCP
