# Ingress rules assign a hostname/path to expose particular ports to the public internet
# NOTE: "Host" header must match in order to be routed
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/app-root: "/index.html"
  name: cis-noflo
spec:
  tls:
  - hosts:
    - noflo.cis.ndslabs.org
    secretName: cis-tls-secret
  rules:
  - host: noflo.cis.ndslabs.org
    http:
      paths:
      - path: /
        backend:
          serviceName: noflo-ui
          servicePort: 9999
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: cis-prototype
spec:
  tls:
  - hosts:
    - proto.cis.ndslabs.org
    secretName: cis-tls-secret
  rules:
  - host: proto.cis.ndslabs.org
    http:
      paths:
      - path: /
        backend:
          serviceName: cis-prototype
          servicePort: 80
      - path: /api
        backend:
          serviceName: cis-prototype
          servicePort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cloud9
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - cloud9.cis.ndslabs.org
    secretName: cis-tls-secret
  rules:
  - host: cloud9.cis.ndslabs.org
    http:
      paths:
      - path: /
        backend:
          serviceName: cloud9
          servicePort: 80
