# Ingress rules assign a hostname/path to expose particular ports to the public internet
# NOTE: "Host" header must match in order to be routed
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: cis-ui
spec:
  tls:
  - hosts:
    - www.cis.ndslabs.org
    secretName: cis-tls-secret
  rules:
  - host: www.cis.ndslabs.org
    http:
      paths:
      - path: /
        backend:
          serviceName: cis-girder
          servicePort: 80
      - path: /girder
        backend:
          serviceName: cis-girder
          servicePort: 8080
      - path: /static
        backend:
          serviceName: cis-girder
          servicePort: 8080
      - path: /api
        backend:
          serviceName: cis-girder
          servicePort: 8080
# TODO: Tie into Kubernetes OAuth?
# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: cis-auth
#   annotations:
#     "nginx.ingress.kubernetes.io/auth-url": "https://www.cis.ndslabs.org/oauth2/auth"
#     "nginx.ingress.kubernetes.io/auth-signin": "https://www.cis.ndslabs.org/oauth2/sign_in"
#     "nginx.ingress.kubernetes.io/ssl-redirect": "true"
#     "nginx.ingress.kubernetes.io/force-ssl-redirect": "true"
# spec:
#   tls:
#   - hosts:
#     - www.cis.ndslabs.org
#     secretName: ndslabs-tls-secret
#   rules:
#   - host: www.cis.ndslabs.org
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: cis-girder
#           servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cloud9
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - cloud9.cis.ndslabs.org
    secretName: cis-tls-secret
  rules:
  - host: cloud9.cis.ndslabs.org
    http:
      paths:
      - path: /
        backend:
          serviceName: cloud9
          servicePort: 80
