apiVersion: batch/v1
kind: Job
metadata:
  name: sc-test
spec:
  template:
    metadata:
      name: sc-test
    spec:
      containers:
      - name: samples-clustering
#        image: knowengdev/samples_clustering_pipeline:04_26_2017
        image: bodom0015/samples-clustering
        env:

        # ANALYSIS_METHOD=[nmf|cc_nmf|net_nmf|cc_net_nmf]
        - name: ANALYSIS_METHOD
#          value: "{{ analysis_method }}"
          value: "cc_net_nmf"


        # Path and file name of the 4 col network file
        - name: GG_NETWORK_NAME_FULL_PATH
#          value: "{{ gg_network_name_full_path }}"
          value: "../data/networks/keg_ST90_4col.edge"

        # Path and file name of user supplied gene sets (aka "features file")
        - name: SPREADSHEET_NAME_FULL_PATH
#          value: "{{ spreadsheet_name_full_path }}"
          value: "../data/spreadsheets/tcga_ucec_somatic_mutation_data.df"

        # Path and file name of user supplied phenotype response file (aka "response file")
        - name: PHENOTYPE_NAME_FULL_PATH
#          value: "{{ phenotype_name_full_path }}"
          value: "../data/spreadsheets/UCEC_phenotype.txt"

        # Threshold
        - name: THRESHOLD
#          value: {{ threshold }}
          value: "10"


        # Path where the results files should be stored
        - name: RESULTS_DIRECTORY
#          value: "{{ results_directory }}"
          value: "./run_dir/results"

        # Path where the temporary files should be stored
        - name: TMP_DIRECTORY
#          value: "{{ tmp_directory }}"
          value: "./run_dir/results/tmp"


        # Number of random samplings
        - name: NUMBER_OF_BOOTSTRAPS
#          value: "{{ number_of_bootstraps }}"
          value: "4"

        - name: NUMBER_OF_CLUSTERS
#          value: {{ number_of_clusters }}
          value: "3"

        # Select 80% of spreadsheet columns
        - name: COLS_SAMPLING_FRACTION
#          value: "{{ cols_sampling_fraction }}"
          value: "0.8"

        # Select 80% of spreadsheet rows
        - name: ROWS_SAMPLING_FRACTION
#          value: "{{ rows_sampling_fraction }}"
          value: "0.8"


        - name: NMF_CONV_CHECK_FREQ
#          value: "{{ nmf_conv_check_freq }}"
          value: "50"

        - name: NMF_MAX_INVARIANCE
#          value: "{{ nmf_max_invariance }}"
          value: "200"

        - name: NMF_MAX_ITERATIONS
#          value: "{{ nmf_max_iterations }}"
          value: "10000"

        - name: NMF_PENALTY_PARAMETER
#          value: "{{ nmf_penalty_parameter }}"
          value: "1400"


        # Maximum number of iterations without convergence in random walk with restart
        - name: RWR_MAX_ITERATIONS
#          value: "{{ rwr_max_iterations }}"
          value: "100"

        # Frobenius norm tolerence of spreadsheet vector in random walk
        - name: RWR_CONVERGENCE_TOLERANCE
#          value: "{{ rwr_convergence_tolerance }}"
          value: "0.0001"

        # Restart probability in random walk: alpha in V_(n+1) = alpha * N * Vn + (1-alpha) * Vo
        - name: RWR_RESTART_PROBABILITY
#          value: "{{ rwr_restart_probability }}"
          value: "0.7"       


        # Number of top genes selected
        - name: TOP_NUMBER_OF_GENES
#          value: "{{ top_number_of_genes }}"
          value: "100"

        # processing_method dictionary, valid values are serial, parallel, dist_comp
        # single core machine: set the processing_method value to be serial
        # multi core machine: set the processing_method value to be parallel
        # multi node machine: set the processing_method value to be dist_comp 
        - name: PROCESSING_METHOD
#          value: "{{ processing_method }}"
          value: "serial"

        # TODO: How best to pass arrays? Space-delimited strings?
        - name: CLUSTER_IP_ADDRESSES
          value: ""

        - name: CLUSTER_SHARED_RAM
#          value: "{{ cluster_shared_ram }}"
          value: "/mnt/ramdisk/knoweng/"

        - name: CLUSTER_SHARED_VOLUME
#          value: "{{ cluster_shared_volume }}"
          value: "/mnt/clustershare/knoweng/"

        volumeMounts:
        - mountPath: /home/test/run_dir
          name: rundir
      volumes:
      - name: rundir
        hostPath:
          path:  /var/glfs/global/jobs/samples-clustering
      restartPolicy: Never
