FROM ndslabs/cloud9-nodejs:latest

ENV K8S_VERSION="1.18.6"
ENV NODEJS_VERSION="12.14.1"

RUN npm install -g n && \
    n ${NODEJS_VERSION} && \
    ln -sf /usr/local/n/versions/node/${NODEJS_VERSION}/bin/node /usr/bin/node

# Install kubectl binary
ADD https://storage.googleapis.com/kubernetes-release/release/v${K8S_VERSION}/bin/linux/amd64/kubectl /usr/bin/kubectl
RUN chmod +x /usr/bin/kubectl

# Install dependency for Docker
RUN apt-get update && apt-get install -y libltdl7 && rm -rf /var/lib/apt/lists/*
