# Ingress rules assign a hostname/path to expose particular ports to the public internet
# NOTE: "Host" header must match in order to be routed
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # TODO: Tie into Kubernetes OAuth?
  name: cis-ui
spec:
  tls:
  - hosts:
    - www.cis.ndslabs.org
    secretName: cis-tls-secret
  rules:
  - host: www.cis.ndslabs.org
    http:
      paths:
      - path: /
        backend:
          serviceName: cis-girder
          servicePort: 80
      - path: /girder/
        backend:
          serviceName: cis-girder
          servicePort: 8080
      - path: /static/
        backend:
          serviceName: cis-girder
          servicePort: 8080
      - path: /api/v1/
        backend:
          serviceName: cis-girder
          servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: cis-girder
  name: cis-girder
spec:
  ports:
  - name: http
    port: 80
  - name: admin
    port: 8080
  selector:
    component: cis-girder
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: cis-girder
  name: cis-girder
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: cis-girder
    spec:
      volumes:
      - name: mongodata
        hostPath:
          path: /home/ubuntu/mongodata
      - name: pluginsrc
        hostPath:
          path: /home/ubuntu/cis-girder-plugin
      - name: uisrc
        hostPath:
          path: /home/ubuntu/cis-ui
      containers:
      - image: cropsinsilico/cis-ui
        imagePullPolicy: Always
        name: cis-ui
        ports:
        - containerPort: 80
        volumeMounts:
        - name: uisrc
          mountPath: /usr/share/nginx/html
      - image: cropsinsilico/girder:2.3.0
        imagePullPolicy: Always
        name: girder
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: pluginsrc
          mountPath: /girder/plugins/cis
      - image: mongo:3.3
        imagePullPolicy: Always
        name: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodata
          mountPath: /data/db
