apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cis-tls
spec:
  secretName: cis-tls-secret
  dnsNames:
  - cis.ndslabs.org
  - staging.cis.ndslabs.org
  - dev.cis.ndslabs.org
  - cloud9.cis.ndslabs.org
  - jupyterlab.cis.ndslabs.org
  - hub.cis.ndslabs.org
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - cis.ndslabs.org
      - staging.cis.ndslabs.org
      - dev.cis.ndslabs.org
      - cloud9.cis.ndslabs.org
      - jupyterlab.cis.ndslabs.org
      - hub.cis.ndslabs.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
